### ISSUE TITLE
Parse null values

### ISSUE THREAD

**Issue by Oleg2tor** [tj/node-querystring#102]
```
console.log(qs.stringify({ foo: null }));
=> foo=

console.log(qs.parse('foo='));
=> { foo: '' }
console.log(qs.parse('foo=null'));
=> { foo: 'null' }
```

But, how can I get "clear" null (not as string)?

**Comment by jonathanong** [comment]
impossible without being too opinionated.

**Comment by rlidwka** [comment]
_crazy idea_: parse values using YAML spec

`qs` could add a reviver for that (like one in JSON.parse)
