### ISSUE TITLE
npm install querystring fails

### ISSUE THREAD

**Issue by Maff-** [tj/node-querystring#2]
When trying to install node-querystring with the given instructions from the readme it fails:
    $ npm install querystring
    npm info it worked if it ends with ok
    npm info using npm@0.2.17
    npm info using node@v0.3.8-pre
    npm ERR! Error: 404 Not Found: querystring
    [...]
    npm ERR! 404 Looks like 'querystring' is not in the npm registry.
    npm ERR! 404 You should bug the author to publish it.
    npm ERR! 404 Note that you can also install from a tarball or local folder.

A search reveals it's listed as "qs" in the npm registry:
    $ npm search querystring
    npm info it worked if it ends with ok
    npm info using npm@0.2.17
    npm info using node@v0.3.8-pre
    [...]
    qs@0.0.1          =tjholowaychuk active installed latest remote   querystring parser
    npm ok

**Comment by tj** [comment]
sorry, forgot to push the readme update. I did rename it to `qs` so it does not conflict with the old core mod
