### ISSUE TITLE
clean up messy stringify tests

### ISSUE THREAD

**Issue by tj** [tj/node-querystring#25]

**Comment by sebs** [comment]
starting to work on this atm

**Comment by sebs** [comment]
still working on it see here 

https://github.com/sebs/node-querystring/

**Comment by sebs** [comment]
I will need some help naming those nested cases. They are not comprehensible to me by just reading the input and output. We could split that up in multiple types of nesting.

**Comment by buschtoens** [comment]
Can't really help you as I'm on my iPhone right now.

Sometimes we can't really find meaningful names, because the tests grow to abstract. Try using the literal query string. We just have to identify it anyhow.

I'll take a look at your cases anyway and try to come up with names. ;)

**Comment by sebs** [comment]
Cool, since I rewrote all the tests from stringify to parse (#facepalm) ... I have to work a bit more. Its good for the structure though

**Comment by sebs** [comment]
https://github.com/visionmedia/node-querystring/pull/81

Named, resorted and done as far as I am concerned. Please merge or comment ;)
