### ISSUE TITLE
urlencoded strings not handled properly

### ISSUE THREAD

**Issue by qzaidi** [tj/node-querystring#43]
I am submitting a form where the '=' character is present, although its urlencoded.

querystring fails to handle this, but node's builitin querystring module handles it just fine.

qs.parse('tBK0FKOvgZw%3D=Uu%2BujGnmB1Y%3D')

should return 

{ 'tBK0FKOvgZw=': 'Uu+ujGnmB1Y=' } (and this is what the builtin module returns)

but it gives this instead

{ 'tBK0FKOvgZw': '=Uu+ujGnmB1Y=' }

**Comment by tj** [comment]
we must be doing an indexOf after decoding, I'll look

**Comment by qzaidi** [comment]
Yes, it url decodes first and then takes the first equality sign it finds.
