### ISSUE TITLE
Add a `.npmignore` file to prevent useless stuff from getting in the npm distro

### ISSUE THREAD

**Issue by balupton** [tj/node-querystring#46]
Things like the tests, examples, etc are not required for the npm distribution, and thus only add to the weight of the package without any use. It would be nice if these were included in a `.npmignore` file - see https://npmjs.org/doc/developers.html#Keeping-files-out-of-your-package

**Comment by tj** [comment]
pull-request! less effort than writing all that out :p

**Comment by buschtoens** [comment]
Closed by dbebf9882abce48ff910c8ea9c3e63fc0554241a.
