### ISSUE TITLE
Using in Browser

### ISSUE THREAD

**Issue by TimNZ** [tj/node-querystring#68]
This a complete noob question that could apply to any node js module that could work in the browser.

How are you using this in the browser? I've done a make but no obvious browser version appears.

I'm using requirejs and can wrap this in a define() but want to see if I'm missing something very obvious here, thanks for any flames :)

**Comment by TimNZ** [comment]
I guess this is related to component.json and Component? More things to learn...

**Comment by buschtoens** [comment]
node-querystring has no external dependencies, so you could use [index.js](https://github.com/visionmedia/node-querystring/blob/master/index.js) right away, without any build-step whatsoever. Just wrap it in your preferred loader (like component's [require.js](https://github.com/component/require)), so it has an `exports` variable to use.

And if you'd like the comfort of using [component(1)](http://component.io/visionmedia/node-querystring), you can list this component as a dependency of your app.
