### ISSUE TITLE
node v0.11 parse includes __proto__

### ISSUE THREAD

**Issue by jonathanong** [tj/node-querystring#82]
node v0.11.8

``` js
> qs.parse('user=tobi')
{ user: 'tobi', [__proto__]: {} }
```

whyyyyyy!? also, this is in REPL and `JSON.stringify()`ing. not sure if it's an actual issue.

**Comment by eivindfjeldstad** [comment]
behaviour of `__proto__` was changed in v8 at some point. It's no longer a problem on qs master, I think. probably needs a version bump

**Comment by buschtoens** [comment]
@jonathanong I'm marking this as closed. If it wasn't fixed already, @eivindfjeldstad's e25892fd10c45061cbb36f38f2184886426b14bb should do the trick.
