### ISSUE TITLE
Use this in the browser without using component.js?

### ISSUE THREAD

**Issue by jisaacks** [tj/node-querystring#90]
Is there anyway to install for use in the browser without using **component.js**?

I am working on a project that I would like to make depend on this project. My project will able to be installed by including a .js file for use in the browser.

I don't want to have to tell people to go install **component.js** just to install a dependency when my project doesn't even use **component.js**.

I can see the source in `index.js` just defines everything globally, so it cannot be installed directly.

It would be nice if there was a generated `qs.js` (or whatever you want to name it) that could be installed directly and hosted on a cdn.

**Comment by tj** [comment]
yup `component build --standalone qs` should do it, giving you the `qs` global

**Comment by jisaacks** [comment]
That worked. Thanks.
