### ISSUE TITLE
Add "license" and "licenses" to package.json

### ISSUE THREAD

**Issue by garthk** [tj/node-querystring#91]
Specifying your [license](https://npmjs.org/doc/json.html#license) in `package.json` makes it a lot easier for your users to find and comply with [GNU Affero](http://www.gnu.org/licenses/agpl-3.0.html) licenses. 

Also giving `licenses` (an array of objects with `type` and `url` keys) helps  users whose legal departments request both the license name _and the text_. See this example from [async](https://npmjs.org/package/async):

```
  "licenses": [{
    "type": "MIT",
    "url": "https://github.com/caolan/async/raw/master/LICENSE"
  }]
```

Though `licenses` isn't specified in the [npm package.json spec](https://npmjs.org/doc/json.html#license), it _is_ supported by the NPM site, as you'll see if you check [async's NPM page](https://npmjs.org/package/async). 

Thanks!

**Comment by rlidwka** [comment]
> makes it a lot easier for your users to find and comply with GNU Affero licenses. 

why people using MIT-licensed package need to comply with GNU Affero licenses?

**Comment by buschtoens** [comment]
As all projects of TJ, this one's MIT as well. Go ahead and do a PR.

However, I don't see a convincing reason for adding the licenses array. A copy of the MIT license is appended to the readme, which is also part of the npm tarball. You will  be automatically provided with the license, when you download this module. In addition to that it's really not that difficult to find the MIT license on the net. Apart from that, every serious software company should know the mainstream licenses.

So, I ask you to go forth and submit a PR adding `"license": "MIT"` to the `package.json` _without_ the `licenses` array.

Thank you for your interest and participation!

**Comment by garthk** [comment]
I was hoping to avoid forking a few dozen repos to make such minor changes, but so be it. 

The license text, if present, trumps the title. I'm afraid my legal department insists on checking both. Breaking LICENSE out to its own file and pointing at it with `licenses` makes that a _lot_ easier.

**Comment by buschtoens** [comment]
Because I have empathy, too. Haha. :D /re visionmedia/jade#1374
